### PR TITLE
update telegraf and influxdb to 0.11.1

### PR DESCRIPTION
**Pull request by girgen**
Hi @cheffo,

I've updated the ports. Do you think I shall commit them to the ports tree?

If you want to stay on as maintainer, no problem.

Palle girgen@FreeBSD.org

### CODE REVIEW

**Comment by dmptrluke** [comment]
Version 12 has dropped now, of both projects

**Comment by girgen** [comment]
Hi @cheffo,
Shall I add the telegraf port 0.12?

**Comment by cheffo** [comment]
I've updated to 0.13.0 both ports. :)

**Comment by girgen** [comment]
I updated the port to 0.13.1 last night. :)

**Pull request closed without merging**
